/**
 * Login
 */
export const TOGGLE_PRODUCT_FILTER = 'TOGGLE_PRODUCT_FILTER';
export const UPDATE_PRODUCT_SEARCH = 'UPDATE_PRODUCT_SEARCH';
export const UPDATE_PRODUCT_STARTAT = 'UPDATE_PRODUCT_STARTAT';
export const UPDATE_PRODUCT_LOCATION = 'UPDATE_PRODUCT_LOCATION';
export const UPDATE_PRODUCT_CONDITION = 'UPDATE_PRODUCT_CONDITION';
export const UPDATE_PRODUCT_PRICING = 'UPDATE_PRODUCT_PRICING';
export const UPDATE_PRODUCT_CATEGORY = 'UPDATE_PRODUCT_CATEGORY';
export const UPDATE_PRODUCT_COLOR = 'UPDATE_PRODUCT_COLOR';

export const UPDATE_PRODUCTS_VIEW_SCROLL_TOP = 'UPDATE_PRODUCTS_VIEW_SCROLL_TOP';
export const IDLE_PRODUCT_SEARCH = 'IDLE_PRODUCT_SEARCH';
export const SUBMIT_PRODUCT_SEARCH = 'SUBMIT_PRODUCT_SEARCH';

/**
 *
 */
export const GET_DASHBOARD_PRODUCTS_REQUEST = 'GET_DASHBOARD_PRODUCTS_REQUEST';
export const GET_DASHBOARD_PRODUCTS_SUCCESS = 'GET_DASHBOARD_PRODUCTS_SUCCESS';
export const GET_DASHBOARD_PRODUCTS_FAILURE = 'GET_DASHBOARD_PRODUCTS_FAILURE';
export const GET_DASHBOARD_PRODUCTS_IDLE = 'GET_DASHBOARD_PRODUCTS_IDLE';

export const GET_PRODUCT_GROUPS_REQUEST = 'GET_PRODUCT_GROUPS_REQUEST';
export const GET_PRODUCT_GROUPS_SUCCESS = 'GET_PRODUCT_GROUPS_SUCCESS';
export const GET_PRODUCT_GROUPS_FAILURE = 'GET_PRODUCT_GROUPS_FAILURE';
export const GET_PRODUCT_GROUPS_IDLE = 'GET_PRODUCT_GROUPS_IDLE';

export const GET_PRODUCT_GROUP_REQUEST = 'GET_PRODUCT_GROUP_REQUEST';
export const GET_PRODUCT_GROUP_SUCCESS = 'GET_PRODUCT_GROUP_SUCCESS';
export const GET_PRODUCT_GROUP_FAILURE = 'GET_PRODUCT_GROUP_FAILURE';
export const GET_PRODUCT_GROUP_IDLE = 'GET_PRODUCT_GROUP_IDLE';

export const POST_PRODUCT_GROUP_REQUEST = 'POST_PRODUCT_GROUP_REQUEST';
export const POST_PRODUCT_GROUP_SUCCESS = 'POST_PRODUCT_GROUP_SUCCESS';
export const POST_PRODUCT_GROUP_FAILURE = 'POST_PRODUCT_GROUP_FAILURE';
export const POST_PRODUCT_GROUP_IDLE = 'POST_PRODUCT_GROUP_IDLE';

export const PUT_PRODUCT_GROUP_REQUEST = 'PUT_PRODUCT_GROUP_REQUEST';
export const PUT_PRODUCT_GROUP_SUCCESS = 'PUT_PRODUCT_GROUP_SUCCESS';
export const PUT_PRODUCT_GROUP_FAILURE = 'PUT_PRODUCT_GROUP_FAILURE';
export const PUT_PRODUCT_GROUP_IDLE = 'PUT_PRODUCT_GROUP_IDLE';

export const DELETE_PRODUCT_GROUP_REQUEST = 'DELETE_PRODUCT_GROUP_REQUEST';
export const DELETE_PRODUCT_GROUP_SUCCESS = 'DELETE_PRODUCT_GROUP_SUCCESS';
export const DELETE_PRODUCT_GROUP_FAILURE = 'DELETE_PRODUCT_GROUP_FAILURE';
export const DELETE_PRODUCT_GROUP_IDLE = 'DELETE_PRODUCT_GROUP_IDLE';

/**
 *
 */
export const GET_PRODUCT_CATEGORIES_REQUEST = 'GET_PRODUCT_CATEGORIES_REQUEST';
export const GET_PRODUCT_CATEGORIES_SUCCESS = 'GET_PRODUCT_CATEGORIES_SUCCESS';
export const GET_PRODUCT_CATEGORIES_FAILURE = 'GET_PRODUCT_CATEGORIES_FAILURE';
export const GET_PRODUCT_CATEGORIES_IDLE = 'GET_PRODUCT_CATEGORIES_IDLE';

export const GET_PRODUCT_CATEGORY_REQUEST = 'GET_PRODUCT_CATEGORY_REQUEST';
export const GET_PRODUCT_CATEGORY_SUCCESS = 'GET_PRODUCT_CATEGORY_SUCCESS';
export const GET_PRODUCT_CATEGORY_FAILURE = 'GET_PRODUCT_CATEGORY_FAILURE';
export const GET_PRODUCT_CATEGORY_IDLE = 'GET_PRODUCT_CATEGORY_IDLE';

export const POST_PRODUCT_CATEGORY_REQUEST = 'POST_PRODUCT_CATEGORY_REQUEST';
export const POST_PRODUCT_CATEGORY_SUCCESS = 'POST_PRODUCT_CATEGORY_SUCCESS';
export const POST_PRODUCT_CATEGORY_FAILURE = 'POST_PRODUCT_CATEGORY_FAILURE';
export const POST_PRODUCT_CATEGORY_IDLE = 'POST_PRODUCT_CATEGORY_IDLE';

export const PUT_PRODUCT_CATEGORY_REQUEST = 'PUT_PRODUCT_CATEGORY_REQUEST';
export const PUT_PRODUCT_CATEGORY_SUCCESS = 'PUT_PRODUCT_CATEGORY_SUCCESS';
export const PUT_PRODUCT_CATEGORY_FAILURE = 'PUT_PRODUCT_CATEGORY_FAILURE';
export const PUT_PRODUCT_CATEGORY_IDLE = 'PUT_PRODUCT_CATEGORY_IDLE';

export const DELETE_PRODUCT_CATEGORY_REQUEST = 'DELETE_PRODUCT_CATEGORY_REQUEST';
export const DELETE_PRODUCT_CATEGORY_SUCCESS = 'DELETE_PRODUCT_CATEGORY_SUCCESS';
export const DELETE_PRODUCT_CATEGORY_FAILURE = 'DELETE_PRODUCT_CATEGORY_FAILURE';
export const DELETE_PRODUCT_CATEGORY_IDLE = 'DELETE_PRODUCT_CATEGORY_IDLE';

/**
 *
 */
export const GET_FUNNEL_PAGES_REQUEST = 'GET_FUNNEL_PAGES_REQUEST';
export const GET_FUNNEL_PAGES_SUCCESS = 'GET_FUNNEL_PAGES_SUCCESS';
export const GET_FUNNEL_PAGES_FAILURE = 'GET_FUNNEL_PAGES_FAILURE';
export const GET_FUNNEL_PAGES_IDLE = 'GET_FUNNEL_PAGES_IDLE';

export const GET_FUNNEL_PAGE_REQUEST = 'GET_FUNNEL_PAGE_REQUEST';
export const GET_FUNNEL_PAGE_SUCCESS = 'GET_FUNNEL_PAGE_SUCCESS';
export const GET_FUNNEL_PAGE_FAILURE = 'GET_FUNNEL_PAGE_FAILURE';
export const GET_FUNNEL_PAGE_IDLE = 'GET_FUNNEL_PAGE_IDLE';

export const POST_FUNNEL_PAGE_REQUEST = 'POST_FUNNEL_PAGE_REQUEST';
export const POST_FUNNEL_PAGE_SUCCESS = 'POST_FUNNEL_PAGE_SUCCESS';
export const POST_FUNNEL_PAGE_FAILURE = 'POST_FUNNEL_PAGE_FAILURE';
export const POST_FUNNEL_PAGE_IDLE = 'POST_FUNNEL_PAGE_IDLE';

export const PUT_FUNNEL_PAGE_REQUEST = 'PUT_FUNNEL_PAGE_REQUEST';
export const PUT_FUNNEL_PAGE_SUCCESS = 'PUT_FUNNEL_PAGE_SUCCESS';
export const PUT_FUNNEL_PAGE_FAILURE = 'PUT_FUNNEL_PAGE_FAILURE';
export const PUT_FUNNEL_PAGE_IDLE = 'PUT_FUNNEL_PAGE_IDLE';

export const DELETE_FUNNEL_PAGE_REQUEST = 'DELETE_FUNNEL_PAGE_REQUEST';
export const DELETE_FUNNEL_PAGE_SUCCESS = 'DELETE_FUNNEL_PAGE_SUCCESS';
export const DELETE_FUNNEL_PAGE_FAILURE = 'DELETE_FUNNEL_PAGE_FAILURE';
export const DELETE_FUNNEL_PAGE_IDLE = 'DELETE_FUNNEL_PAGE_IDLE';

/**
 *
 */
export const POST_DASHBOARD_AUTH_REQUEST = 'POST_DASHBOARD_AUTH_REQUEST';
export const POST_DASHBOARD_AUTH_SUCCESS = 'POST_DASHBOARD_AUTH_SUCCESS';
export const POST_DASHBOARD_AUTH_FAILURE = 'POST_DASHBOARD_AUTH_FAILURE';
export const POST_DASHBOARD_AUTH_IDLE = 'POST_DASHBOARD_AUTH_IDLE';

/**
 *
 */

export const GET_PRODUCT_ENQUIRIES_REQUEST = 'GET_PRODUCT_ENQUIRIES_REQUEST';
export const GET_PRODUCT_ENQUIRIES_SUCCESS = 'GET_PRODUCT_ENQUIRIES_SUCCESS';
export const GET_PRODUCT_ENQUIRIES_FAILURE = 'GET_PRODUCT_ENQUIRIES_FAILURE';
export const GET_PRODUCT_ENQUIRIES_IDLE = 'GET_PRODUCT_ENQUIRIES_IDLE';

export const POST_PRODUCT_ENQUIRY_REQUEST = 'POST_PRODUCT_ENQUIRY_REQUEST';
export const POST_PRODUCT_ENQUIRY_SUCCESS = 'POST_PRODUCT_ENQUIRY_SUCCESS';
export const POST_PRODUCT_ENQUIRY_FAILURE = 'POST_PRODUCT_ENQUIRY_FAILURE';
export const POST_PRODUCT_ENQUIRY_IDLE = 'POST_PRODUCT_ENQUIRY_IDLE';
